version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag test:latest 426604611868.dkr.ecr.ap-south-1.amazonaws.com/test
  post_build:
    commands:
      - docker push 426604611868.dkr.ecr.ap-south-1.amazonaws.com/test
      - printf '[{"name":helloworld,"imageUri":"%s"}]' 426604611868.dkr.ecr.ap-south-1.amazonaws.com/test > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
